declare var React: any
declare var ReactDOM: any
declare var ReactRouterDOM: any
declare var Link: any
declare var Route: any
declare var Switch: any
declare var Redirect: any
declare var BrowserRouter: any
declare var DEV: boolean
