/* eslint-disable object-curly-newline */
module.exports = (db) => {
  console.log('Inserting default data');

  return Promise.resolve()
    .then(() => db.Language.create({ name: 'russian' }))
    .then(() => db.Language.create({ name: 'english' }))
    .then(() => db.Language.create({ name: 'german' }))

    .then(() => db.Rubric.create({ name: 'test rubric 1' }))
    .then(() => db.Rubric.create({ name: 'test rubric 2' }))

    .then(() => db.Deck.create({ name: 'deck 1', level: 'elementary', type: 'private' }))
    .then(() => db.Deck.create({ name: 'deck 2', level: 'intermediate', type: 'private' }))
    .then(() => db.Deck.create({ name: 'deck 3', level: 'elementary', type: 'public', RubricId: 1 }))
    .then(() => db.Deck.create({ name: 'deck 4', level: 'intermediate', type: 'public', RubricId: 2 }))
    .then(() => db.Deck.create({ name: 'deck 5', level: 'elementary', type: 'paid', RubricId: 2 }))
    .then(() => db.Deck.create({ name: 'deck 6', level: 'intermediate', type: 'paid', RubricId: 2 }))

    .then(() => db.User.create({ local_name: 'Test User', email: 'test@user.ru', access_group: 'user', password: '123' }))
    .then(() => db.User.create({ local_name: 'Test Admin', email: 'test@admin.ru', access_group: 'admin', password: '123' }))

    .then(() => db.UserDeck.create({ DeckId: '1', UserId: '1' }))
    .then(() => db.UserDeck.create({ DeckId: '2', UserId: '1' }))
    .then(() => db.UserDeck.create({ DeckId: '3', UserId: '1' }))

    .then(() => db.UserDeck.create({ DeckId: '4', UserId: '2' }))
    .then(() => db.UserDeck.create({ DeckId: '5', UserId: '2' }))
    .then(() => db.UserDeck.create({ DeckId: '6', UserId: '2' }))

    // .then(() => db.Deck.create({ name: 'deck 1', level: 1, type: 'free', rubric_id: 1 }))
    // .then(() => db.Deck.create({ name: 'deck 2', level: 1, type: 'free', rubric_id: 1 }))
    // .then(() => db.Deck.create({ name: 'deck 3', level: 1, type: 'free', rubric_id: 2 }))
    // .then(() => db.Deck.create({ name: 'deck 4', level: 2, type: 'free', rubric_id: 1 }))
    // .then(() => db.Deck.create({ name: 'deck 5', level: 2, type: 'free', rubric_id: 1 }))
    // .then(() => db.Deck.create({ name: 'deck 6', level: 2, type: 'free', rubric_id: 2 }))

    // .then(() => db.Word.create({ russian: 'абажур', english: 'shade', german: 'lampenschirm' }))
    // .then(() => db.Word.create({ russian: 'аббревиатура', english: 'abbreviation', german: 'abkürzung' }))
    // .then(() => db.Word.create({ russian: 'абитуриент', english: 'enrollee', german: 'antragsteller' }))
    // .then(() => db.Word.create({ russian: 'абонемент', english: 'subscription', german: 'abo' }))
    // .then(() => db.Word.create({ russian: 'аборт', english: 'abortion', german: 'eine abtreibung' }))
    // .then(() => db.Word.create({ russian: 'абракадабра', english: 'abracadabra', german: 'abrakadabra' }))
    // .then(() => db.Word.create({ russian: 'абсент', english: 'absinthe', german: 'absinth' }))
    // .then(() => db.Word.create({ russian: 'авария', english: 'crash', german: 'ein unfall' }))
    // .then(() => db.Word.create({ russian: 'авгур', english: 'augur', german: 'augur' }))
    // .then(() => db.Word.create({ russian: 'автокефалия', english: 'autocephaly', german: 'autozephalie' }))
    // .then(() => db.Word.create({ russian: 'агальма', english: 'agalma', german: 'agalma' }))
    // .then(() => db.Word.create({ russian: 'агломерат', english: 'agglomerate', german: 'agglomerat' }))
    // .then(() => db.Word.create({ russian: 'аграф', english: 'agraf', german: 'agraf' }))
    // .then(() => db.Word.create({ russian: 'адепт', english: 'adept', german: 'geschickt' }))
    // .then(() => db.Word.create({ russian: 'адмирал', english: 'admiral', german: 'admiral' }))
    // .then(() => db.Word.create({ russian: 'ажиотаж', english: 'stir', german: 'rühren' }))
    // .then(() => db.Word.create({ russian: 'азарт', english: 'excitement', german: 'aufregung' }))
    // .then(() => db.Word.create({ russian: 'акант', english: 'acanthus', german: 'akanthus' }))
    // .then(() => db.Word.create({ russian: 'аквилон', english: 'aquilon', german: 'aquilon' }))
    // .then(() => db.Word.create({ russian: 'аккламация', english: 'acclamation', german: 'akklamation' }))
    // .then(() => db.Word.create({ russian: 'акколада', english: 'accolade', german: 'auszeichnung' }))
    // .then(() => db.Word.create({ russian: 'аккордеон', english: 'accordion', german: 'akkordeon' }))
    // .then(() => db.Word.create({ russian: 'акрибия', english: 'acribia', german: 'acribia' }))
    // .then(() => db.Word.create({ russian: 'акробатика', english: 'acrobatics', german: 'akrobatik' }))
    // .then(() => db.Word.create({ russian: 'акростих', english: 'acrostic', german: 'akrostichon' }))
    // .then(() => db.Word.create({ russian: 'аксиология', english: 'axiology', german: 'axiologie' }))
    // .then(() => db.Word.create({ russian: 'акупунктура', english: 'acupuncture', german: 'akupunktur' }))
    // .then(() => db.Word.create({ russian: 'акут', english: 'acute', german: 'akut' }))
    // .then(() => db.Word.create({ russian: 'акушер', english: 'obstetrician', german: 'geburtshelfer' }))
    // .then(() => db.Word.create({ russian: 'алеаторика', english: 'aleatoric', german: 'aleatorisch' }))
    // .then(() => db.Word.create({ russian: 'алембик', english: 'alembic', german: 'alembic' }))
    // .then(() => db.Word.create({ russian: 'алиби', english: 'alibi', german: 'alibi' }))
    // .then(() => db.Word.create({ russian: 'алкоголь', english: 'alcohol', german: 'alkohol' }))
    // .then(() => db.Word.create({ russian: 'аллергия', english: 'allergy', german: 'allergie' }))
    // .then(() => db.Word.create({ russian: 'аллюзия', english: 'allusion', german: 'anspielung' }))
    // .then(() => db.Word.create({ russian: 'алтын', english: 'Altyn', german: 'altyn' }))
    // .then(() => db.Word.create({ russian: 'альбом', english: 'album', german: 'ein album' }))
    // .then(() => db.Word.create({ russian: 'альвеолы', english: 'alveoli', german: 'alveolen' }))
    // .then(() => db.Word.create({ russian: 'альков', english: 'alcove', german: 'nische' }))
    // .then(() => db.Word.create({ russian: 'альманах', english: 'almanac', german: 'almanach' }))
    // .then(() => db.Word.create({ russian: 'альтруизм', english: 'altruism', german: 'altruismus' }))
    // .then(() => db.Word.create({ russian: 'аляповатый', english: 'coarse', german: 'grob' }))
    // .then(() => db.Word.create({ russian: 'амазонка', english: 'amazon', german: 'amazon' }))
    // .then(() => db.Word.create({ russian: 'амальгама', english: 'amalgam', german: 'amalgam' }))
    // .then(() => db.Word.create({ russian: 'амбивалентный', english: 'ambivalent', german: 'ambivalent' }))
    // .then(() => db.Word.create({ russian: 'амбиция', english: 'ambition', german: 'ehrgeiz' }))
    // .then(() => db.Word.create({ russian: 'амбразура', english: 'embrasure', german: 'lücke' }))
    // .then(() => db.Word.create({ russian: 'амбушюр', english: 'ear cushion', german: 'ohrkissen' }))
    // .then(() => db.Word.create({ russian: 'амнистия', english: 'amnesty', german: 'amnestie' }))
    // .then(() => db.Word.create({ russian: 'амортизация', english: 'depreciation', german: 'abschreibung' }))
    // .then(() => db.Word.create({ russian: 'амортизация', english: 'depreciation', german: 'abschreibung' }))
    // .then(() => db.Word.create({ russian: 'ампельные', english: 'ampelous', german: 'ampel' }))
    // .then(() => db.Word.create({ russian: 'амплуа', english: 'role', german: 'rolle' }))
    // .then(() => db.Word.create({ russian: 'амуниция', english: 'ammunition', german: 'munition' }))
    // .then(() => db.Word.create({ russian: 'амфора', english: 'amphora', german: 'amphore' }))
    // .then(() => db.Word.create({ russian: 'анаколуф', english: 'anacoluthon', german: 'anacoluf' }))
    // .then(() => db.Word.create({ russian: 'анафема', english: 'anathema', german: 'anathema' }))
    // .then(() => db.Word.create({ russian: 'анафора', english: 'anaphora', german: 'anaphora' }))
    // .then(() => db.Word.create({ russian: 'ангажемент', english: 'engagement', german: 'engagement' }))
    // .then(() => db.Word.create({ russian: 'анева', english: 'aneva', german: 'aneva' }))
    // .then(() => db.Word.create({ russian: 'анекдот', english: 'joke', german: 'anekdote' }))
    // .then(() => db.Word.create({ russian: 'анестезия', english: 'anesthesia', german: 'anästhesie' }))
    // .then(() => db.Word.create({ russian: 'анналы', english: 'annals', german: 'annalen' }))
    // .then(() => db.Word.create({ russian: 'аномалия', english: 'anomaly', german: 'anomalie' }))
    // .then(() => db.Word.create({ russian: 'антидатировать', english: 'antidate', german: 'gegenmittel' }))
    // .then(() => db.Word.create({ russian: 'антимоний', english: 'antimonium', german: 'antimonium' }))
    // .then(() => db.Word.create({ russian: 'антология', english: 'anthology', german: 'anthologie' }))
    // .then(() => db.Word.create({ russian: 'антресоли', english: 'mezzanine', german: 'mezzanine' }))
    // .then(() => db.Word.create({ russian: 'антропоморфизм', english: 'anthropomorphism', german: 'anthropomorphismus' }))
    // .then(() => db.Word.create({ russian: 'антураж', english: 'entourage', german: 'entourage' }))
    // .then(() => db.Word.create({ russian: 'анфилада', english: 'enfilade', german: 'enfilade' }))
    // .then(() => db.Word.create({ russian: 'анчоус', english: 'anchovy', german: 'sardelle' }))
    // .then(() => db.Word.create({ russian: 'апатит', english: 'apatite', german: 'apatit' }))
    // .then(() => db.Word.create({ russian: 'апелляция', english: 'appeal', german: 'berufung' }))
    // .then(() => db.Word.create({ russian: 'апломб', english: 'aplomb', german: 'souverän' }))
    // .then(() => db.Word.create({ russian: 'апокриф', english: 'apocrypha', german: 'apokryphen' }))
    // .then(() => db.Word.create({ russian: 'апологет', english: 'apologist', german: 'apologet' }))
    // .then(() => db.Word.create({ russian: 'апостроф', english: 'apostrophe', german: 'apostroph' }))
    // .then(() => db.Word.create({ russian: 'апофема', english: 'apothem', german: 'apothem' }))
    // .then(() => db.Word.create({ russian: 'апофеоз', english: 'apotheosis', german: 'apotheose' }))
    // .then(() => db.Word.create({ russian: 'аппетит', english: 'appetite', german: 'appetit' }))
    // .then(() => db.Word.create({ russian: 'апробация', english: 'approbation', german: 'approbation' }))
    // .then(() => db.Word.create({ russian: 'аптека', english: 'pharmacy', german: 'apotheke' }))
    // .then(() => db.Word.create({ russian: 'арабеска', english: 'arabesque', german: 'arabeske' }))
    // .then(() => db.Word.create({ russian: 'арапник', english: 'arapnik', german: 'arapnik' }))
    // .then(() => db.Word.create({ russian: 'арбуз', english: 'watermelon', german: 'wassermelone' }))
    // .then(() => db.Word.create({ russian: 'арена', english: 'arena', german: 'arena' }))
    // .then(() => db.Word.create({ russian: 'ареология', english: 'areology', german: 'areologie' }))
    // .then(() => db.Word.create({ russian: 'арматура', english: 'fittings', german: 'beschläge' }))
    // .then(() => db.Word.create({ russian: 'армяк', english: 'armyak', german: 'armyak' }))
    // .then(() => db.Word.create({ russian: 'арпеджио', english: 'arpeggio', german: 'arpeggio' }))
    // .then(() => db.Word.create({ russian: 'арсенал', english: 'arsenal', german: 'arsenal' }))
    // .then(() => db.Word.create({ russian: 'артачиться', english: 'jiggle', german: 'wackeln' }))
    // .then(() => db.Word.create({ russian: 'артефакт', english: 'artifact', german: 'artefakt' }))
    // .then(() => db.Word.create({ russian: 'артикул', english: 'vendor code', german: 'artikelnummer' }))
    // .then(() => db.Word.create({ russian: 'артиллерия', english: 'artillery', german: 'artillerie' }))
    // .then(() => db.Word.create({ russian: 'архимандрит', english: 'archimandrite', german: 'archimandrit' }))
    // .then(() => db.Word.create({ russian: 'архипелаг', english: 'archipelago', german: 'archipel' }))
    // .then(() => db.Word.create({ russian: 'архитектоника', english: 'architectonics', german: 'architektonik' }))
    // .then(() => db.Word.create({ russian: 'асимптота', english: 'asymptote', german: 'asymptote' }))
    // .then(() => db.Word.create({ russian: 'аскорбиновая', english: 'ascorbic', german: 'ascorbie' }))
    // .then(() => db.Word.create({ russian: 'аспект', english: 'aspect', german: 'aspekt' }))
    // .then(() => db.Word.create({ russian: 'аспид', english: 'asp', german: 'asp' }))
    // .then(() => db.Word.create({ russian: 'аспид', english: 'asp', german: 'asp' }))
    // .then(() => db.Word.create({ russian: 'астения', english: 'asthenia', german: 'asthenie' }))
    // .then(() => db.Word.create({ russian: 'астроблема', english: 'astrobleme', german: 'unglück' }))
    // .then(() => db.Word.create({ russian: 'атавизм', english: 'atavism', german: 'atavismus' }))
    // .then(() => db.Word.create({ russian: 'атаман', english: 'chieftain', german: 'häuptling' }))
    // .then(() => db.Word.create({ russian: 'ателье', english: 'studio', german: 'atelier' }))
    // .then(() => db.Word.create({ russian: 'аттик', english: 'attic', german: 'dachboden' }))
    // .then(() => db.Word.create({ russian: 'аудиенция', english: 'audience', german: 'publikum' }))
    // .then(() => db.Word.create({ russian: 'аудитор', english: 'auditor', german: 'der wirtschaftsprüfer' }))
    // .then(() => db.Word.create({ russian: 'аукцион', english: 'auction', german: 'auktion' }))
    // .then(() => db.Word.create({ russian: 'аускультация', english: 'auscultation', german: 'auskultation' }))
    // .then(() => db.Word.create({ russian: 'аутентичный', english: 'authentic', german: 'authentisch' }))
    // .then(() => db.Word.create({ russian: 'аутодафе', english: 'auto-da-fe', german: 'auto-da-fe' }))
    // .then(() => db.Word.create({ russian: 'афиша', english: 'poster', german: 'poster' }))
    // .then(() => db.Word.create({ russian: 'афоризм', english: 'aphorism', german: 'aphorismus' }))
    // .then(() => db.Word.create({ russian: 'аффект', english: 'affect', german: 'beeinflussen' }))
    // .then(() => db.Word.create({ russian: 'аффинаж', english: 'refining', german: 'verfeinern' }))
    // .then(() => db.Word.create({ russian: 'аффинный', english: 'affine', german: 'affine' }))
    // .then(() => db.Word.create({ russian: 'ахимса', english: 'ahimsa', german: 'ahimsa' }))
    // .then(() => db.Word.create({ russian: 'ахинея', english: 'nonsense', german: 'unsinn' }))

    // .then(() => db.UserdeckWord.create({ deck_id: 1, word_id: 1 }))
    // .then(() => db.UserdeckWord.create({ deck_id: 1, word_id: 2 }))
    // .then(() => db.UserdeckWord.create({ deck_id: 1, word_id: 3 }))
    // .then(() => db.UserdeckWord.create({ deck_id: 1, word_id: 4 }))
    // .then(() => db.UserdeckWord.create({ deck_id: 1, word_id: 5 }))

    // .then(() => db.UserdeckWord.create({ deck_id: 2, word_id: 6 }))
    // .then(() => db.UserdeckWord.create({ deck_id: 2, word_id: 7 }))
    // .then(() => db.UserdeckWord.create({ deck_id: 2, word_id: 8 }))
    // .then(() => db.UserdeckWord.create({ deck_id: 2, word_id: 9 }))
    // .then(() => db.UserdeckWord.create({ deck_id: 2, word_id: 10 }))

    // .then(() => db.UserdeckWord.create({ deck_id: 3, word_id: 11 }))
    // .then(() => db.UserdeckWord.create({ deck_id: 3, word_id: 12 }))
    // .then(() => db.UserdeckWord.create({ deck_id: 3, word_id: 13 }))
    // .then(() => db.UserdeckWord.create({ deck_id: 3, word_id: 14 }))
    // .then(() => db.UserdeckWord.create({ deck_id: 3, word_id: 15 }))

    // .then(() => db.UserdeckWord.create({ user_id: 1, deck_id: 1, word_id: 1 }))
    // .then(() => db.UserdeckWord.create({ user_id: 1, deck_id: 1, word_id: 2 }))
    // .then(() => db.UserdeckWord.create({ user_id: 1, deck_id: 1, word_id: 3 }))
    // .then(() => db.UserdeckWord.create({ user_id: 1, deck_id: 1, word_id: 4 }))
    // .then(() => db.UserdeckWord.create({ user_id: 1, deck_id: 1, word_id: 5 }))

    // .then(() => db.UserdeckWord.create({ user_id: 1, deck_id: 2, word_id: 6 }))
    // .then(() => db.UserdeckWord.create({ user_id: 1, deck_id: 2, word_id: 7 }))
    // .then(() => db.UserdeckWord.create({ user_id: 1, deck_id: 2, word_id: 8 }))
    // .then(() => db.UserdeckWord.create({ user_id: 1, deck_id: 2, word_id: 9 }))
    // .then(() => db.UserdeckWord.create({ user_id: 1, deck_id: 2, word_id: 10 }))

    // .then(() => db.UserdeckWord.create({ user_id: 1, deck_id: 3, word_id: 11 }))
    // .then(() => db.UserdeckWord.create({ user_id: 1, deck_id: 3, word_id: 12 }))
    // .then(() => db.UserdeckWord.create({ user_id: 1, deck_id: 3, word_id: 13 }))
    // .then(() => db.UserdeckWord.create({ user_id: 1, deck_id: 3, word_id: 14 }))
    // .then(() => db.UserdeckWord.create({ user_id: 1, deck_id: 3, word_id: 15 }))

    // .then(() => db.UserdeckWord.create({ user_id: 2, deck_id: 1, word_id: 1 }))
    // .then(() => db.UserdeckWord.create({ user_id: 2, deck_id: 1, word_id: 2 }))
    // .then(() => db.UserdeckWord.create({ user_id: 2, deck_id: 1, word_id: 3 }))
    // .then(() => db.UserdeckWord.create({ user_id: 2, deck_id: 1, word_id: 4 }))
    // .then(() => db.UserdeckWord.create({ user_id: 2, deck_id: 1, word_id: 5 }))

    // .then(() => db.UserdeckWord.create({ user_id: 2, deck_id: 2, word_id: 6 }))
    // .then(() => db.UserdeckWord.create({ user_id: 2, deck_id: 2, word_id: 7 }))
    // .then(() => db.UserdeckWord.create({ user_id: 2, deck_id: 2, word_id: 8 }))
    // .then(() => db.UserdeckWord.create({ user_id: 2, deck_id: 2, word_id: 9 }))
    // .then(() => db.UserdeckWord.create({ user_id: 2, deck_id: 2, word_id: 10 }))

    // .then(() => db.UserdeckWord.create({ user_id: 2, deck_id: 3, word_id: 11 }))
    // .then(() => db.UserdeckWord.create({ user_id: 2, deck_id: 3, word_id: 12 }))
    // .then(() => db.UserdeckWord.create({ user_id: 2, deck_id: 3, word_id: 13 }))
    // .then(() => db.UserdeckWord.create({ user_id: 2, deck_id: 3, word_id: 14 }))
    // .then(() => db.UserdeckWord.create({ user_id: 2, deck_id: 3, word_id: 15 }))
};
